name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        compiler: [ gcc, clang, msvc ]
        exclude:
          # Exclude gcc and clang on Windows, use only msvc
          - os: windows-latest
            compiler: clang
          - os: windows-latest
            compiler: gcc
          # Exclude msvc on Ubuntu as it's not commonly used
          - os: ubuntu-latest
            compiler: msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build project
        run: |
          cmake --build build --parallel

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --verbose

      - name: Upload build artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.compiler }}
          path: build/
          retention-days: 7

  # Additional job for code quality checks
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git clang-format

      - name: Check code formatting
        run: |
          # Check if C files in src/ and include/ are properly formatted
          find src/ include/ -name "*.c" -o -name "*.h" | xargs clang-format --dry-run --Werror